# netlify.toml

[build]
  command = "# no build command"
  publish = "."
  functions = "netlify/functions"

# 规则一：将所有聊天相关的请求转发到 proxy-api 函数
[[redirects]]
  from = "/api/chat/*"
  to = "/.netlify/functions/proxy-api/:splat"
  status = 200

# 规则二：将测试连接的请求转发到 test-connection 函数
[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test-connection"
  status = 200

# 规则三：将语音合成(TTS)的请求转发到 tts 函数
[[redirects]]
  from = "/api/tts"
  to = "/.netlify/functions/tts"
  status = 200
