# netlify.toml

[build]
  command = "# no build command"
  publish = "."
  functions = "netlify/functions"

# 注意：proxy-api 和 test-connection 功能已改为前端直接调用，不再需要重定向规则

# 规则三：将数据传输请求转发到 transfer-data 函数
# 请求路径: /api/transfer-data
[[redirects]]
  from = "/api/transfer-data"
  to = "/.netlify/functions/transfer-data"
  status = 200
